#pragma once
#include <stdint.h>

typedef enum {
    STATE_INIT = 0,
    STATE_WIFI_CONNECT,
    STATE_WIFI_SUCCESS,
    STATE_WIFI_ERROR,
    STATE_RUNNING,
    STATE_MQTT_ERROR,
    STATE_LOGOUT,
    STATE_USER_PASS,
    STATE_USER_PASSWORD_ERROR,
    STATE_NEW_USER_PASS,
    STATE_CONTINUE,
    STATE_SAVED_WIFI,
    STATE_DELETE_WIFI_OPTION,
    STATE_MENU,
    STATE_DEVICE_LIST,
    STATE_SERVICE_LIST,
    STATE_SERVICE_POSITON,
    STATE_WIFI_INPUT,
    STATE_USER_LIST,
    STATE_NO_DATA,
    STATE_DELETE_USER_PASS,
    STATE_FULL_USER_PASS,
    STATE_SAVED_WIFI_OPTION,
    STATE_NO_WIFI,
    STATE_AUTO_CONNECT,
    STATE__AUTO_CONNECT_WIFI,
    STATE_CONNECTING_WIFI,
} SystemState;

typedef enum {
    DISPLAY_IDLE = 0,
    DISPLAY_WIFI_CONNECTING = 1,
    DISPLAY_WIFI_SUCCESS = 2,
    DISPLAY_WIFI_ERROR = 3,
    DISPLAY_MQTT_CONNECTING = 4,
    DISPLAY_MAIN_SCREEN = 5,
    DISPLAY_MQTT_ERROR = 6,
    DISPLAY_LOGOUT=7,
    DISPLAY_USER_PASS=8,
    DISPLAY_USER_PASSWORD_ERROR=9,
    DISPLAY_NEW_USER_PASS=10,
    DISPLAY_CONTINUE=11,
    DISPLAY_SAVED_WIFI=12,
    DISPLAY_DELET_WIFI_OPTION=13,
    DISPLAY_MENU=14,
    DISPLAY_DEVICE_LIST=15,
    DISPLAY_SERVICE_LIST=16,
    DISPLAY_SERVICE_POSITION=17,
    DISPLAY_WIFI_INPUT=18,
    DISPLAY_USER_LIST=19,
    DISPLAY_NO_DATA=20,
    DISPLAY_DELETE_USER_PASS=21,
    DISPLAY_FULL_USER_PASS=22,
    DISPLAY_SAVED_WIFI_OPTION=23,
    DISPLAY_NO_WIFI=24,
    DISPLAY_AUTO_CONNECT=25,
    DISPLAY_AUTO_CONNECT_WIFI=26,
    DISPLAY_CONNECTING_WIFI=27,


} DisplayState;


typedef struct {
      
    char ssid[33];
    char pass[64];
    uint8_t bssid[6];
} wifi_ap_info;

typedef struct {
     uint8_t count;
     wifi_ap_info aps[5];
}  wifi_list;
